import { PackageJson } from "../schemas/PackageJson";
import { Builder } from "./Builder";
import { ClaspJson } from "../schemas/ClaspJson";

export class ReadmeBuilder extends Builder {

  packageJson: PackageJson;
  claspJson: ClaspJson;

  constructor(packageJson: PackageJson, claspJson: ClaspJson) {
    super()
    this.packageJson = packageJson;
    this.claspJson = claspJson;
  }

  public build(): Builder {
    this
    .append("# Summary").doubleLine()
    .append(`This package contains type definitions for [${this.extractHomepage()}](${this.claspJson.library.name})`).doubleLine()
    .append("# Instalation").doubleLine()
    .append('```').line()
    .append(`i -S ${this.packageJson.name}-dts`).line()
    .append('or').doubleLine()
    .append(`yarn add --dev ${this.packageJson.name}-dts`).line()
    .append('```').doubleLine()
    .append('## Details').doubleLine()
    .append(`Generated by [clasp-dts](https://github.com/maelcaldas/clasp-dts) on ${new Date().toLocaleDateString("en-US")}`).doubleLine()
    return this;
  }

  extractHomepage(): string {
    if (this.packageJson.homepage) {
      return this.packageJson.homepage
    }
    if (this.packageJson.repository) {
      if (typeof this.packageJson.repository === 'string') {
        return this.packageJson.repository;
      } else {
        return this.packageJson.repository.url.replace('\\.git', '');
      }
    }
    return 'https://developers.google.com/apps-script/guides/libraries';
  }
}